import { test, expect } from '@playwright/test';
import { fixtureTrack, policyText, query, storefrontFixture } from './storefront-fixture';

test('track navigation preserves filters, a single native audio owner and seeking', async ({ page }, testInfo) => {
  const fixture = await storefrontFixture(page);
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/' + query);
  const row = page.getByRole('article', { name: fixtureTrack.title, exact: true });
  await row.getByRole('button', { name: `Play ${fixtureTrack.title}`, exact: true }).click();
  await expect(page.getByRole('button', { name: 'Pause preview', exact: true })).toBeVisible();
  await expect.poll(() => page.evaluate(() => window.__nativePreviews[0]?.currentTime ?? 0)).toBeGreaterThan(0);
  const seek = page.getByRole('slider', { name: 'Seek preview' });
  await expect(seek).toBeEnabled();
  const box = await seek.boundingBox();
  expect(box).not.toBeNull();
  await seek.click({ position: { x: box!.width / 2, y: box!.height / 2 } });
  await expect.poll(() => page.evaluate(() => window.__nativePreviews[0].currentTime)).toBeGreaterThan(20);
  const timeBefore = await page.evaluate(() => window.__nativePreviews[0].currentTime);
  await row.getByRole('link', { name: fixtureTrack.title, exact: true }).click();
  await expect(page).toHaveURL(fixtureTrack.shareUrl + query);
  const heading = page.getByRole('heading', { name: fixtureTrack.title, level: 1 });
  await expect(heading).toBeVisible();
  await expect(heading).toBeFocused();
  expect(await page.evaluate(() => window.__nativePreviews.length)).toBe(1);
  expect(await page.evaluate(() => window.__nativePreviews[0].paused)).toBe(false);
  expect(await page.evaluate(() => window.__nativePreviews[0].currentTime)).toBeGreaterThanOrEqual(timeBefore);
  await expect(page.getByRole('button', { name: `Pause ${fixtureTrack.title}`, exact: true }).first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'Back to results' })).toHaveAttribute('href', '/' + query);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('track-detail-playing.png'), fullPage: true });
  await page.getByRole('link', { name: 'Back to results' }).click();
  await expect(page).toHaveURL('/' + query);
  await expect(page.getByRole('searchbox', { name: 'Search tracks' })).toHaveValue('Synthetic');
  await expect(page.getByRole('button', { name: 'Pause preview', exact: true })).toBeVisible();
  expect(fixture.navigation).toEqual([fixtureTrack.shareUrl + query, '/' + query]);
  expect(await page.evaluate(() => window.__nativePreviews.length)).toBe(1);
  await page.getByRole('button', { name: 'Pause preview', exact: true }).click();
  expect(await page.evaluate(() => window.__nativePreviews[0].paused)).toBe(true);
  expect(errors).toEqual([]);
});

test('full license disclosure recovers, follows the selected offer and supports keyboard dismissal', async ({ page }, testInfo) => {
  const fixture = await storefrontFixture(page, { failFirstTerms: true });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.goto(fixtureTrack.shareUrl + query);
  const launch = page.getByRole('button', { name: 'Read terms & choose', exact: true }).first();
  await launch.focus();
  await launch.press('Enter');
  const dialog = page.getByRole('dialog', { name: 'CHOOSE YOUR LICENSE.' });
  await expect(dialog).toBeVisible();
  await expect(dialog.getByRole('alert')).toContainText('These terms could not be loaded.');
  await dialog.getByRole('button', { name: 'Retry terms' }).click();
  const text = dialog.getByRole('region', { name: 'Published license text' });
  await expect(text).toHaveText(policyText(0));
  await expect(page.locator('#policy-injection')).toHaveCount(0);
  const extended = dialog.getByRole('radio', { name: /Extended test license/ });
  await extended.check();
  await expect(text).toHaveText(policyText(1));
  await text.focus();
  await text.press('End');
  expect(await text.evaluate(element => element.scrollTop > 0)).toBe(true);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('full-license-disclosure.png'), fullPage: false });
  await page.keyboard.press('Escape');
  await expect(dialog).not.toBeVisible();
  await expect(launch).toBeFocused();
  expect(fixture.termsRequests()).toBe(3);
  expect(await page.evaluate(() => window.__nativePreviews.length)).toBe(0);
});
